apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: delay
        image: busybox:latest
        command: ['sleep', '15']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80