apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: delay
        image: busybox:1.28
        command:
          - sh
          - -c 
          - 'until nslookup nginx-svc; do echo "Waiting for the availability of the service"; sleep 2; done'
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80